const ENV = {
	SERVER_META_URL: process.env.NEXT_PUBLIC_SERVER_META_URL,
	SERVER_API_URL: process.env.NEXT_PUBLIC_SERVER_API_URL,
	OLD_SERVER_API_URL: process.env.NEXT_PUBLIC_SERVER_URL,
};
export default ENV;
