import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { HeadCombinedData } from "@/model/DVM/meta.dvm";
import SEO from "@/helper/SEO";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export async function getSSideProps() {
	const meta: HeadCombinedData = {
		title: "Welcome to WBC",
		metaNames: [
			{
				content: "Meta Property Content WBC",
				key: "MetaPropertyKeyWBC",
				property: "MetaPropertyWBC",
			},
		],
		metaProperties: [
			{
				content: "Meta Name Content WBC",
				key: "MetaNameKeyWBC",
				property: "MetaNameWBC",
			},
		],
	};

	return {
		props: {
			meta: meta,
		},
	};
}
export default async function RootLayout({
	meta,
	children,
}: Readonly<{
	meta: HeadCombinedData;
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>{SEO.setSEO(meta)}</head>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
